### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by ghost** [CDDLeiden/PCMol#5]
Hi, on WSL2 Debian I followed

1. Setup script (recommended)

At the end of the installation I see the following error:

`Testing the installation... Generating SMILES for P29275 (A2AR_HUMAN) using the pretrained model.
Traceback (most recent call last):
  File "/home/evehom/pcmol/pcmol/generate.py", line 2, in <module>
    from pcmol.models.runner import Runner
  File "/home/evehom/pcmol/pcmol/__init__.py", line 1, in <module>
    from .models.runner import Runner
  File "/home/evehom/pcmol/pcmol/models/__init__.py", line 1, in <module>
    from .transformer import AF2SmilesTransformer, count_parameters
  File "/home/evehom/pcmol/pcmol/models/transformer.py", line 1, in <module>
    import torch
  File "/home/evehom/miniconda3/envs/pcmol/lib/python3.10/site-packages/torch/__init__.py", line 367, in <module>
    from torch._C import *  # noqa: F403
ImportError: /home/evehom/miniconda3/envs/pcmol/lib/python3.10/site-packages/torch/lib/../../nvidia/cusparse/lib/libcusparse.so.12: undefined symbol: __nvJitLinkComplete_12_4, version libnvJitLink.so.12
**************`

Please advise on how to resolve this. Thanks/Evert

**Comment by andriusbern** [comment]
Hi!
This seems like an error with your GPU, it might be not compatible or outdated. To test whether you can run the model at all on this device try running it on the CPU by:

`python pcmol/generate.py --target P29275 --device cpu`

**Comment by ghost** [comment]
Doing so gives me the same error:

```
(pcmol) evehom@everthodell:~/pcmol$ python pcmol/generate.py --target P29275 --device cpu
Traceback (most recent call last):
  File "/home/evehom/pcmol/pcmol/generate.py", line 2, in <module>
    from pcmol.models.runner import Runner
  File "/home/evehom/pcmol/pcmol/__init__.py", line 1, in <module>
    from .models.runner import Runner
  File "/home/evehom/pcmol/pcmol/models/__init__.py", line 1, in <module>
    from .transformer import AF2SmilesTransformer, count_parameters
  File "/home/evehom/pcmol/pcmol/models/transformer.py", line 1, in <module>
    import torch
  File "/home/evehom/miniconda3/envs/pcmol/lib/python3.10/site-packages/torch/__init__.py", line 367, in <module>
    from torch._C import *  # noqa: F403
ImportError: /home/evehom/miniconda3/envs/pcmol/lib/python3.10/site-packages/torch/lib/../../nvidia/cusparse/lib/libcusparse.so.12: undefined symbol: __nvJitLinkComplete_12_4, version libnvJitLink.so.12
```
 This is on WSL2 Debian 12. NVIDIA RTX A500 GPU, NVIDIA driver 552.74 , Cuda 12.2

**Comment by andriusbern** [comment]
I updated the conda environment spec to be more suited for windows systems as well. I cannot test it myself, however you can try to remove the `pcmol` conda environment and then rerun the installation instructions (after pull/clone) to see if this is resolved.

**Comment by ghost** [comment]
```
Testing the installation... Generating SMILES for P29275 (A2AR_HUMAN) using the pretrained model.
Loading model from /home/evehom/Programs/pcmol/data/models/XL
Loading config from /home/evehom/Programs/pcmol/data/models/XL/config.yaml
Loaded model XL, parameter count: 101340995
Model directory: /home/evehom/Programs/pcmol/data/models/XL20241226-170805, checkpoint: 7

 0 P29275
 Downloading AlphaFold embeddings for P29275 to </home/evehom/Programs/pcmol/data/alphafold>...
 Downloading from https://surfdrive.surf.nl/files/index.php/s/Gqy5vPOYJUHVaU7/download\?path\=%2F\&files\=P29275.zip...
Loading AlphaFold2 <structure> embeddings...
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 870.91it/s]
********************************************************************************
Generating smiles for target P29275...
100%|███████████████████████████████████████████████████████████████████████████████████| 10/10 [00:29<00:00,  2.92s/it]
Valid smiles: 10.0 / 10
Unique smiles: 10 / 10
    Evaluating 10 SMILES strings...

Saved results to /home/evehom/Programs/pcmol/data/results/XL20241226-170805
                                                    target  train  valid  ...  aromatic_rings  num_rings  heavy_atoms
CCCn1c(=O)c2[nH]c(C3CCCC3)nc2n(CC)c1=O              P29275      0   True  ...               2          3           21
Cn1cnc2c(N)nc(OCc3ocnc3C#CCOc3ccccc3)cc21           P29275      0   True  ...               4          4           28
CC1=CC2CC(C1)CC2C(=O)c1cc(OCc2nc3cc(C)ccc3[nH]2...  P29275      0   True  ...               3          5           29
OC1C(CF)OC(n2cnc3c(NCc4ccccc4)nc(NCc4cccc(F)c4)...  P29275      0   True  ...               4          5           35
CNc1nc2nnc(COC3CCCCC3)n2c2sccc12                    P29275      0   True  ...               3          4           22
COc1ccc(CN2CCN(S(=O)(=O)c3ccc(-c4nc5c(=O)n(CC(C...  P29275      0   True  ...               4          6           43
Cn1c(=O)c2[nH]c(-c3ccc(OCC(=O)O)cc3)cc2n(C)c1=O     P29275      0   True  ...               3          3           24
CCn1c(=O)c2[nH]c(-c3ccccc3Cl)nc2n(CC2CCCC(C(=O)...  P29275      0   True  ...               4          5           36
Cc1nc(OCC(=O)NNc2nc3ccccc3s2)ccc1-c1cc2c([nH]1)...  P29275      0   True  ...               5          5           35
Cn1c(-c2ccccc2)nc2c(Cl)c(-c3ccco3)c(N)nc21          P29275      0   True  ...               4          4           23

[10 rows x 13 columns]
**************

Installation complete. You can now use the package by activating the conda environment using
        conda activate pcmol

To generate SMILES for a target protein, use the following command:
        python pcmol/generate.py --target <accession_ID>

For example, to generate SMILES for P29275 (A2AR_HUMAN), use the following command:
        python pcmol/generate.py --target P29275

*If no GPU is available, the generation process may take a long time. Additional flag must be used when generating without GPU:
        python pcmol/generate.py --target P29275 --device cpu

For more information, use the following command:
        python pcmol/generate.py --help
**************
```

All good now!  Thanks for your patience/Evert
